 version: 2
 jobs:
   build:
     docker:
       - image: circleci/golang:1.12
     steps:
       - checkout
       - run: go get github.com/bwmarrin/discordgo
       - run: go vet
       - run: go build
